- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - global_serif_font_size is defined
      - firefox_mono_font_size_ratio is defined
      - firefox_sans_font_size_ratio is defined
      - firefox_serif_font_size_ratio is defined
      - firefox_zoom_level is defined

- name: Configuring firefox
  ansible.builtin.debug:
    msg: "Placeholder role: firefox"
