- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - jetbrains_mono_font_size_ratio is defined
      - jetbrains_sans_font_size_ratio is defined

- name: Configuring jetbrains mono font size
  ansible.builtin.debug:
    msg: "JetBrains mono font size: {{ (global_mono_font_size * jetbrains_mono_font_size_ratio) | round }}"

- name: Configuring jetbrains sans font size
  ansible.builtin.debug:
    msg: "JetBrains sans font size: {{ (global_sans_font_size * jetbrains_sans_font_size_ratio) | round }}"
