- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - jetbrains_mono_font_size_ratio is defined
      - jetbrains_sans_font_size_ratio is defined

- name: Configuring jetbrains
  ansible.builtin.debug:
    msg: "Placeholder role: jetbrains"
