- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - vscode_mono_font_size_ratio is defined
      - vscode_zoom_level is defined

- name: Configuring vscode mono font size
  ansible.builtin.debug:
    msg: "VSCode mono font size: {{ (global_mono_font_size * vscode_mono_font_size_ratio) | round(1, 'common') }}"

- name: Configuring vscode zoom level
  ansible.builtin.debug:
    msg: "VSCode zoom level: {{ vscode_zoom_level }}"
