- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - vscode_mono_font_size_ratio is defined
      - vscode_zoom_level is defined

- name: Configuring vscode
  ansible.builtin.debug:
    msg: "Placeholder role: vscode"
