- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - font_size_mono is defined
      - font_size_ratio_vscode_mono is defined
      - zoom_level_ratio_vscode is defined

- name: Configuring vscode
  ansible.builtin.debug:
    msg: "Placeholder role: vscode"
