- name: "Check if dependent variables are defined"
  assert:
    that:
      - font_size_mono is defined
      - font_size_ratio_neovide_mono is defined

- name: Configuring neovide
  debug:
    msg: "Placeholder role: neovide"
