- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - font_size_mono is defined
      - font_size_ratio_neovide_mono is defined

- name: Configuring neovide
  ansible.builtin.debug:
    msg: "Placeholder role: neovide"
