- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - neovide_mono_font_size_ratio is defined

- name: Configuring neovide
  ansible.builtin.debug:
    msg: "Placeholder role: neovide"
