- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - neovide_mono_font_size_ratio is defined

- name: Configuring neovide mono font size
  ansible.builtin.debug:
    msg: "Neovide mono font size: {{ (global_mono_font_size * neovide_mono_font_size_ratio) | round }}"
