- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - sublimetext_mono_font_size_ratio is defined

- name: Configuring sublimetext
  ansible.builtin.debug:
    msg: "Placeholder role: sublimetext"
