- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - font_size_mono is defined
      - font_size_ratio_sublimetext_mono is defined

- name: Configuring sublimetext
  ansible.builtin.debug:
    msg: "Placeholder role: sublimetext"
