- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - qt_mono_font_size_ratio is defined
      - qt_sans_font_size_ratio is defined

- name: Configuring qt
  ansible.builtin.debug:
    msg: "Placeholder role: qt"
