- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - qt_mono_font_size_ratio is defined
      - qt_sans_font_size_ratio is defined

- name: Configuring qt mono font size
  ansible.builtin.debug:
    msg: "QT mono font size: {{ (global_mono_font_size * qt_mono_font_size_ratio) | round(1, 'common') }}"

- name: Configuring qt sans font size
  ansible.builtin.debug:
    msg: "QT sans font size: {{ (global_sans_font_size * qt_sans_font_size_ratio) | round(1, 'common') }}"
