- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - zed_mono_font_size_ratio is defined
      - zed_sans_font_size_ratio is defined

- name: Configuring zed
  ansible.builtin.debug:
    msg: "Placeholder role: zed"
