- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - zed_mono_font_size_ratio is defined
      - zed_sans_font_size_ratio is defined

- name: Configuring zed mono font size
  ansible.builtin.debug:
    msg: "Zed mono font size: {{ (global_mono_font_size * zed_mono_font_size_ratio) | round(1, 'common') }}"

- name: Configuring zed sans font size
  ansible.builtin.debug:
    msg: "Zed sans font size: {{ (global_sans_font_size * zed_sans_font_size_ratio) | round(1, 'common') }}"
