- name: "Check if dependent variables are defined"
  assert:
    that:
      - font_size_mono is defined
      - font_size_sans is defined
      - font_size_ratio_zed_mono is defined
      - font_size_ratio_zed_sans is defined

- name: Configuring zed
  debug:
    msg: "Placeholder role: zed"
