- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - global_serif_font_size is defined
      - gnome_mono_font_size_ratio is defined
      - gnome_sans_font_size_ratio is defined
      - gnome_serif_font_size_ratio is defined
      - gnome_zoom_level is defined

- name: Configuring gnome
  ansible.builtin.debug:
    msg: "Placeholder role: gnome"
