- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - emacs_mono_font_size_ratio is defined
      - emacs_sans_font_size_ratio is defined

- name: Configuring emacs
  ansible.builtin.debug:
    msg: "Placeholder role: emacs"
