- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - font_size_mono is defined
      - font_size_sans is defined
      - font_size_ratio_emacs_mono is defined
      - font_size_ratio_emacs_sans is defined

- name: Configuring emacs
  ansible.builtin.debug:
    msg: "Placeholder role: emacs"
