- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - emacs_mono_font_size_ratio is defined
      - emacs_sans_font_size_ratio is defined

- name: Configuring emacs mono font size
  ansible.builtin.debug:
    msg: "Emacs mono font size: {{ (global_mono_font_size * emacs_mono_font_size_ratio) | round | int }}"

- name: Configuring emacs sans font size
  ansible.builtin.debug:
    msg: "Emacs sans font size: {{ (global_sans_font_size * emacs_sans_font_size_ratio) | round | int }}"
