- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - x11_mono_font_size_ratio is defined
      - x11_sans_font_size_ratio is defined
      - x11_dpi_setting is defined
      - x11_cursor_size is defined

- name: Configuring x11
  ansible.builtin.debug:
    msg: "Placeholder role: x11"
