- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - global_sans_font_size is defined
      - x11_mono_font_size_ratio is defined
      - x11_sans_font_size_ratio is defined
      - x11_dpi_setting is defined
      - x11_cursor_size is defined

- name: Configuring x11 mono font size
  ansible.builtin.debug:
    msg: "X11 mono font size: {{ (global_mono_font_size * x11_mono_font_size_ratio) | round(1, 'common') }}"

- name: Configuring x11 sans font size
  ansible.builtin.debug:
    msg: "X11 sans font size: {{ (global_sans_font_size * x11_sans_font_size_ratio) | round(1, 'common') }}"

- name: Configuring x11 dpi setting
  ansible.builtin.debug:
    msg: "X11 dpi setting: {{ x11_dpi_setting }}"

- name: Configuring x11 cursor size
  ansible.builtin.debug:
    msg: "X11 cursor size: {{ x11_cursor_size }}"
