- name: "Check if dependent variables are defined"
  ansible.builtin.assert:
    that:
      - global_mono_font_size is defined
      - alacritty_mono_font_size_ratio is defined

- name: Configuring alacritty mono font size
  ansible.builtin.debug:
    msg: "Alacritty mono font size: {{ (global_mono_font_size * alacritty_mono_font_size_ratio) | round }}"
